### ISSUE TITLE
doubt in worksheet 2

### ISSUE THREAD

**Issue by sarvendrasingh** [dbc2201/gla-bcsc0001-2018#11]
how can there be output in any of the programmes as we are using "**printf"** without including **"stdio.h"**

**Comment by nik-1207** [comment]
since it is very frequent to use printf and scanf function in coding that's why updated version it is featured in modern C language

**Comment by sarvendrasingh** [comment]
yeah.. but how is this happening?? it is not showing error but runs after showing **warning**..

**Comment by nik-1207** [comment]
Also this Question was answered by divyansh sir in class  several times
as the compiler was modified to do so

**Comment by g-rishabh** [comment]
gcc compiler understand stdin and stdout so if we don't use stdio.h it explicitly put it in and then compile.

**Comment by sarvendrasingh** [comment]
but this is only in the case of gcc na??
what if i compile using any other compiler..

**Comment by dbc2201** [comment]
`#include` does not import libraries, it merely pastes files into your source code at compile time. The `<stdio.h>` header contains (directly or indirectly) certain prototypes, but the library has to be linked in separately. Since `printf` is usually in a library that is linked to programs by default, you usually don't have to do anything to use `printf`.
