### ISSUE TITLE
I couldn't understand how to get actual output  of question  11 and 12  of worksheet 4

### ISSUE THREAD

**Issue by ANSHIKAGUPTA1301** [dbc2201/gla-bcsc0001-2018#24]
Q-11
#include <stdio.h>
int a;
int b;
int c;
int main()
{
    if( a == b == b == c)
    {
	    printf("%d %d %d", a, b, c);
    }
    return 0;
}

Q-12
#include <stdio.h>
int a = 10;
int b = 10;
int c = 10;
int main()
{
    if(a == b == b == c)
    {
	    printf("%d %d %d", a, b, c);
    }
    return 0;
}

**Comment by dbc2201** [comment]
@ANSHIKAGUPTA1301 
___
[Worksheet 4](https://github.com/dbc2201/gla-bcsc0001-2018/blob/master/Worksheet4.md) : Question 11
Code :
```c
#include <stdio.h>
int a;
int b;
int c;
int main()
{
    if( a == b == b == c)
    {
	    printf("%d %d %d", a, b, c);
    }
    return 0;
}
```
Explanation :
The variables `a`, `b` & `c` are **Global Variables**, meaning that they are accesible througout the program. Unlike local variables, that are bound by the scope of `{ }` pairs. If we have declared a global variable in a program and have not initialized it, the GCC compiler will, *by default*, initialize them to the value `0`. 
So, the value of all the vaiables is set to `0` by the compiler.
Now, the `if()` statement has the test condition
`( a == b == b == c)`
From the rules of precendence and associativity, *or as I fondly like to call it* **PANDA**, we get
`( ( ( a == b ) == b ) ) == c )`
Simply substituting the values to the variables, we get
`( ( ( 0 == 0 ) == 0 ) ) == 0 )`
Now, we just solve the brackets one by one
first the innermost one, *from ( a== b )*
`( 0 == 0 )` will result in 1, because both values are equal.
so, the statement now becomes
`( ( ( 1 ) == 0 ) ) == 0 ) ` or `( ( 1 == 0 ) ) == 0 ) `
Now, similarly, the expression `( 1 == 0 )` will return `0`
because the values are not equal
hence the statement becomes
`( ( 0 ) ) == 0 ) ` or `( 0  == 0 ) `
Which will yield the final result `1`, which is a non-zero value, hence the `if()` will execute it's body.
And since all the values of the variables are zero, the output will be 
`0 0 0`

**Comment by dbc2201** [comment]
Similar will be the working of the `if()` statement in question no 12
