### ISSUE TITLE
Doubt in worksheet2 question10

### ISSUE THREAD

**Issue by Prachibansal2745** [dbc2201/gla-bcsc0001-2018#28]

**Comment by dbc2201** [comment]
@Prachibansal2745, could you tell me what exactly your doubt is? Then I would be able to give you a more specific explanation.

**Comment by Prachibansal2745** [comment]
int main()
{
    int a = 012, b = 034;
	int x = 0x12, y = 0x34;
		int c,d,u,v;
		c=a&b;
		d=a|b;
		u=x&y;
		v=x|y;
		printf("%o %o %x %x",c,d,u,v);
		return 0;
}
What will be the output of this code

**Comment by dbc2201** [comment]
@Prachibansal2745 
The output of the above code is
`10 36 10 36`

**Comment by Prachibansal2745** [comment]
What will be the dry run of this code

**Comment by dbc2201** [comment]
@Prachibansal2745 
___
First, we will take a look at the values that are being initialized in the variables.
Please observe that we have written `012` and not `12`. Both of these values have a different meaning. The value `12` is an `int` type value, as we have already learnt and implemented in the class, but the value `012` is an **octal** number. Another thing to be noticed here is, the operations that are performed on these values are **binary operations**. The important thing to remember about binary operations *is*, they operate on binary values. Hence the value `012` would be converted to the decimal equivalent of the octal number first.
`(012)8 = (10)10`
this means the number `012` in `octal` is equivalent to `10` in `decimal`. Now, we can convert this number into its equivalent `binary` form. 
`(10)10 = (1010)2`
this means that the number `10` in `decimal` is equivalent to `1010` in `binary`. Since we now have the `binary` value, we can apply the `binary`  operation. But the operator being used here is a *binary* operator ( meaning that it needs two operands to work ) and thus, we will need another *binary* value to continue. The next value to convert is `034`. We will repeat the same process for this value as well. This is an `octal` number, 
`(034)8 = (28)10 = (11100)2`
We now have the operator as well as both the operands now.
The expression now becomes, 
`c = 1010 & 11100`
the `binary AND (&)` works as depicted below
`0 & 0 = 0`
`0 & 1 = 0`
`1 & 0 = 0`
`1 & 1 = 0`
thus, the resultant of these values would be
```
      0 1 0 1 0
(&) 1 1 1 0 0
      0 1 0 0 0 <-- Answer
```
Hence the value is (1000)2 = (8)10 = (10)8.
Similarly, we have computed the other operator, the `binary OR ( | )`
it works as depicted below
`0 & 0 = 0`
`0 & 1 = 1`
`1 & 0 = 1`
`1 & 1 = 1`
Also, another thing to be noticed here is, the other values are written as `0x12`. This means these values are in the `hexadecimal` format and would have to be converted to `binary` before we can operate on them.

**Comment by Prachibansal2745** [comment]
Thanks sir

**Comment by dbc2201** [comment]
Please close the issue if you are satisfied with the explanation.
