### ISSUE TITLE
answer of sheet no 6 question no 9

### ISSUE THREAD

**Issue by Kishanlalbind** [dbc2201/gla-bcsc0001-2018#56]
#include<stdio.h>
int add(int x,int y);
int sub(int a,int b);
int mult(int c,int d);
int divide(int e,int f);
int main()
{
  int k,n1,n2;
 printf("enter two number:\n");
 scanf("%d %d",&n1,&n2);
 k = add(n1,n2);
 printf("%d\n",k);
 int l,n3,n4;
  printf("enter two number:\n");
 scanf("%d%d",&n3,&n4);
 l=sub(n3,n4);
 printf("%d\n",l);
 int m,n5,n6;
  printf("enter two number:\n");
 scanf("%d%d",&n5,&n6);
 m=mult(n5,n6);
 printf("%d\n",m);
 int n,n7,n8;
  printf("enter two number:\n");
 scanf("%d%d",&n7,&n8);
 n=divide(n7,n8);
 printf("%d\n",n);
  return 0;
}
int add (int x,int y)
{
    int s;
    s=x+y;
    return s;
}
int sub(int a,int b)
{
    int sb;
    sb=a-b;
    return sb;
}
int mult(int c,int d)
{
    int mt;
    mt=c*d;
    return mt;
}
int divide(int e,int f)
{
    int de;
    de=e/f;
    return de;
}

**Comment by dbc2201** [comment]
@Kishanlalbind 
your code seems to work fine, but it is impossible for the user to understand what is happening by looking at the output screen.
You should give the output like
`printf("%d + %d = %d\n", n1, n2, k);`
instead of 
`printf("%d\n",k);`
Also, no need to take so many variables. You can reuse the variables `n1` and `n2` for all the operations in `main()`

**Comment by dbc2201** [comment]
```c
#include<stdio.h>
int main()
{
    int a;
    printf("Enter number of days\n");
    scanf("%d",&a);
    printf("No. of years %d\n",a /365);
    a = a%365;
    printf("No. of weeks %d\n",a/7);
    a = a%7;
    printf("No. of Days %d\n", a);

    return 0;
}
```
